<?php
/**
 * @filesource feedback_form.moddule
 * @author martin.gonzalez
 */

/**
 * Implementation of hook_enable
 */
function feedback_form_enable() {
	variable_set('feedback_form_node', 51);
}


/**
 * Implementation of hook_init
 */
function feedback_form_init() {
	$nid = variable_get("feedback_form_node", 0);
	if (is_numeric($nid) && $nid > 0) {
		drupal_add_js(array('feedback_form' => array('contact_form' => _get_contact_form($nid))), 'setting');
		drupal_add_js(drupal_get_path('module', 'feedback_form') . '/js/feedback_form.js');
		drupal_add_css(drupal_get_path('module', 'feedback_form') . '/css/feedback_form.css');
	}
}

/**
 * Implementation of hook_menu
 */
function feedback_form_menu() {
	$items['feedback/form/webform/js/submit'] = array(
	  'page callback' => 'feedback_form_webform_js_submit',
	  'access callback' => TRUE,
	);
	return $items;
}

/**
 * Implementation of hook_form_alter
 */
function feedback_form_form_alter(&$form, &$form_state, $form_id) {
	$nid = variable_get("feedback_form_node");
	if( $form_id === 'webform_client_form_' . $nid) {
		unset($form['#action']);
	}
}



/**
 * Devuelve el HTML del formulario
 */
function _get_contact_form($nid) {

	$node = node_load($nid);

	return render(node_view($node, $view_mode = 'full', $langcode = NULL));
}