<?php
/**
 * @filesource home.moddule
 * @author martin.gonzalez
 */

/**
 * Implementation of hook_theme
 */
function home_theme() {
	return array(
			'home_output' => array(	
					'variables' => array(),
					'template' => 'templates/home-output'			
			),
	);
}

/**
 * Implementation of hook_menu
 */
function home_menu() {
	$items['homepage'] = array(
      'page callback' => 'homepage',
	  'access callback' => TRUE,
    );
	$items['ajax/home/rendered'] = array(
	  'page callback' => 'ajax_home_rendered',
	  'access callback' => TRUE,		
	);
    return $items;
}

/**
 * function callback
 */
function homepage() {
	drupal_add_js(drupal_get_path('module', 'home') . '/js/home.js');
	drupal_add_css(drupal_get_path('module', 'home'). '/css/home.css');
	return theme('home_output');
}

/**
 * ajax callback
 */
function ajax_home_rendered() {
	switch ($_POST['option']) {
		
	    case 'blog':
	    	_option_blog();
	    	;
	    break;
	    case 'about':
	    	_option_about_me();
	    break;
	    
		default:
			;
		break;
	}
}
/**
 *
 */
function _option_about_me() {
	$node = node_load(52);

	print render(node_view($node, $view_mode = 'full', $langcode = NULL));
}
/**
 * Display blog in home
 */
function _option_blog() {
	$view_name = 'blog';
	$display_id = 'block';

	$html =	views_embed_view($view_name, $display_id);
	
	print $html;
}
/**
 * template preprocess
 * @param $vars
 */
function template_preprocess_home_output(&$vars) {
	
///	$vars['about'] = _option_about_me();
	
}

